Fix: Typo in package manager detection script

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -45,7 +45,8 @@ jobs:
             echo "runner=npx --no-install" >> $GITHUB_OUTPUT
             exit 0
           else
-            echo "Unable to determine package manager" >> $exit 1
+            echo "Unable to determine package manager"
+            exit 1
           fi
       - name: Setup Node
         uses: actions/setup-node@v4
